// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea1 = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_TextArea1, lv_pct(100));
    lv_obj_set_height(ui_TextArea1, lv_pct(27));
    lv_textarea_set_text(ui_TextArea1, "We");
    lv_textarea_set_placeholder_text(ui_TextArea1, "Placeholder...");

    ui_TextArea2 = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_TextArea2, lv_pct(100));
    lv_obj_set_height(ui_TextArea2, lv_pct(27));
    lv_obj_set_x(ui_TextArea2, lv_pct(0));
    lv_obj_set_y(ui_TextArea2, lv_pct(27));
    lv_textarea_set_text(ui_TextArea2, "Ass");
    lv_textarea_set_placeholder_text(ui_TextArea2, "Placeholder...");

}
