// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_HomePage
void ui_HomePage_screen_init(void);
lv_obj_t * ui_HomePage;
void ui_event_btnMain(lv_event_t * e);
lv_obj_t * ui_btnMain;
lv_obj_t * ui_MainArea;
void ui_event_btnWeather(lv_event_t * e);
lv_obj_t * ui_btnWeather;
void ui_event_btnTime(lv_event_t * e);
lv_obj_t * ui_btnTime;
void ui_event_btnSetting(lv_event_t * e);
lv_obj_t * ui_btnSetting;
lv_obj_t * ui_btnApp;
lv_obj_t * ui_btnSecondary;
lv_obj_t * ui_SecondaryArea;
// CUSTOM VARIABLES
lv_obj_t * uic_HomePage;
lv_obj_t * uic_btnWordbook;
lv_obj_t * uic_MainArea;
lv_obj_t * uic_btnWeather;
lv_obj_t * uic_btnTime;
lv_obj_t * uic_btnSetting;
lv_obj_t * uic_btnApp;
lv_obj_t * uic_btnSecondary;
lv_obj_t * uic_SecondaryArea;

// SCREEN: ui_CalendarPage
void ui_CalendarPage_screen_init(void);
lv_obj_t * ui_CalendarPage;
lv_obj_t * ui_Calendar1;
void ui_event_btnHome(lv_event_t * e);
lv_obj_t * ui_btnHome;
// CUSTOM VARIABLES
lv_obj_t * uic_CalendarPage;

// SCREEN: ui_WeatherPage
void ui_WeatherPage_screen_init(void);
lv_obj_t * ui_WeatherPage;
lv_obj_t * ui_WeatherChart;
lv_obj_t * ui_TextArea1;
void ui_event_btnHome1(lv_event_t * e);
lv_obj_t * ui_btnHome1;
// CUSTOM VARIABLES
lv_obj_t * uic_WeatherChart;

// SCREEN: ui_SettingPage
void ui_SettingPage_screen_init(void);
lv_obj_t * ui_SettingPage;
void ui_event_btnHome3(lv_event_t * e);
lv_obj_t * ui_btnHome3;
lv_obj_t * ui_SettingContainer;
lv_obj_t * ui_wifiContainer;
lv_obj_t * ui_wifiSwitch;
lv_obj_t * ui_wifiTextArea;
lv_obj_t * ui_bleContainer;
lv_obj_t * ui_bleSwitch;
lv_obj_t * ui_bleTextArea;
lv_obj_t * ui_timeContainer;
lv_obj_t * ui_timeModeSwitch;
lv_obj_t * ui_timeTextArea;
lv_obj_t * ui_memorandumContainer;
lv_obj_t * ui_memorandumSwitch;
lv_obj_t * ui_memorandumTextArea;
// CUSTOM VARIABLES
lv_obj_t * uic_SettingPage;
lv_obj_t * uic_SettingContainer;
lv_obj_t * uic_wifiContainer;
lv_obj_t * uic_bleContainer;
lv_obj_t * uic_bleSwitch;
lv_obj_t * uic_bleTextArea;
lv_obj_t * uic_timeContainer;
lv_obj_t * uic_timeSwitch;
lv_obj_t * uic_timeTextArea;
lv_obj_t * uic_memorandumContainer;
lv_obj_t * uic_memorandumSwitch;
lv_obj_t * uic_memorandumTextArea;

// SCREEN: ui_AppPage
void ui_AppPage_screen_init(void);
lv_obj_t * ui_AppPage;
// CUSTOM VARIABLES
lv_obj_t * uic_AppPage;

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_btnMain(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_CalendarPage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_CalendarPage_screen_init);
    }
}

void ui_event_btnWeather(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WeatherPage, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_WeatherPage_screen_init);
    }
}

void ui_event_btnTime(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_CalendarPage, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_CalendarPage_screen_init);
    }
}

void ui_event_btnSetting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingPage, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_SettingPage_screen_init);
    }
}

void ui_event_btnHome(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomePage, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_HomePage_screen_init);
    }
}

void ui_event_btnHome1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomePage, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_HomePage_screen_init);
    }
}

void ui_event_btnHome3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomePage, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_HomePage_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_HomePage_screen_init();
    ui_CalendarPage_screen_init();
    ui_WeatherPage_screen_init();
    ui_SettingPage_screen_init();
    ui_AppPage_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_HomePage);
}
