// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_HomePage
void ui_HomePage_screen_init(void);
extern lv_obj_t * ui_HomePage;
void ui_event_btnMain(lv_event_t * e);
extern lv_obj_t * ui_btnMain;
extern lv_obj_t * ui_MainArea;
void ui_event_btnWeather(lv_event_t * e);
extern lv_obj_t * ui_btnWeather;
void ui_event_btnTime(lv_event_t * e);
extern lv_obj_t * ui_btnTime;
void ui_event_btnSetting(lv_event_t * e);
extern lv_obj_t * ui_btnSetting;
extern lv_obj_t * ui_btnApp;
extern lv_obj_t * ui_btnSecondary;
extern lv_obj_t * ui_SecondaryArea;
// CUSTOM VARIABLES
extern lv_obj_t * uic_HomePage;
extern lv_obj_t * uic_btnWordbook;
extern lv_obj_t * uic_MainArea;
extern lv_obj_t * uic_btnWeather;
extern lv_obj_t * uic_btnTime;
extern lv_obj_t * uic_btnSetting;
extern lv_obj_t * uic_btnApp;
extern lv_obj_t * uic_btnSecondary;
extern lv_obj_t * uic_SecondaryArea;

// SCREEN: ui_CalendarPage
void ui_CalendarPage_screen_init(void);
extern lv_obj_t * ui_CalendarPage;
extern lv_obj_t * ui_Calendar1;
void ui_event_btnHome(lv_event_t * e);
extern lv_obj_t * ui_btnHome;
// CUSTOM VARIABLES
extern lv_obj_t * uic_CalendarPage;

// SCREEN: ui_WeatherPage
void ui_WeatherPage_screen_init(void);
extern lv_obj_t * ui_WeatherPage;
extern lv_obj_t * ui_WeatherChart;
extern lv_obj_t * ui_TextArea1;
void ui_event_btnHome1(lv_event_t * e);
extern lv_obj_t * ui_btnHome1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_WeatherChart;

// SCREEN: ui_SettingPage
void ui_SettingPage_screen_init(void);
extern lv_obj_t * ui_SettingPage;
void ui_event_btnHome3(lv_event_t * e);
extern lv_obj_t * ui_btnHome3;
extern lv_obj_t * ui_SettingContainer;
extern lv_obj_t * ui_wifiContainer;
extern lv_obj_t * ui_wifiSwitch;
extern lv_obj_t * ui_wifiTextArea;
extern lv_obj_t * ui_bleContainer;
extern lv_obj_t * ui_bleSwitch;
extern lv_obj_t * ui_bleTextArea;
extern lv_obj_t * ui_timeContainer;
extern lv_obj_t * ui_timeModeSwitch;
extern lv_obj_t * ui_timeTextArea;
extern lv_obj_t * ui_memorandumContainer;
extern lv_obj_t * ui_memorandumSwitch;
extern lv_obj_t * ui_memorandumTextArea;
// CUSTOM VARIABLES
extern lv_obj_t * uic_SettingPage;
extern lv_obj_t * uic_SettingContainer;
extern lv_obj_t * uic_wifiContainer;
extern lv_obj_t * uic_bleContainer;
extern lv_obj_t * uic_bleSwitch;
extern lv_obj_t * uic_bleTextArea;
extern lv_obj_t * uic_timeContainer;
extern lv_obj_t * uic_timeSwitch;
extern lv_obj_t * uic_timeTextArea;
extern lv_obj_t * uic_memorandumContainer;
extern lv_obj_t * uic_memorandumSwitch;
extern lv_obj_t * uic_memorandumTextArea;

// SCREEN: ui_AppPage
void ui_AppPage_screen_init(void);
extern lv_obj_t * ui_AppPage;
// CUSTOM VARIABLES
extern lv_obj_t * uic_AppPage;

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_weather_png);    // assets/weather.png
LV_IMG_DECLARE(ui_img_time_png);    // assets/time.png
LV_IMG_DECLARE(ui_img_setting_png);    // assets/setting.png
LV_IMG_DECLARE(ui_img_qr_png);    // assets/QR.png
LV_IMG_DECLARE(ui_img_back_png);    // assets/back.png

// FONTS
LV_FONT_DECLARE(ui_font_ChineseSong16);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
