// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_AppPage_screen_init(void)
{
    ui_AppPage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_AppPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AppPage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AppPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_AppPage = ui_AppPage;

}
