// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_CalendarPage_screen_init(void)
{
    ui_CalendarPage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_CalendarPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Calendar1 = lv_calendar_create(ui_CalendarPage);
    lv_calendar_set_today_date(ui_Calendar1, 2025, 4, 21);
    lv_calendar_set_showed_date(ui_Calendar1, 2025, 4);
    lv_obj_t * ui_Calendar1_header = lv_calendar_header_arrow_create(ui_Calendar1);
    lv_obj_set_width(ui_Calendar1, lv_pct(100));
    lv_obj_set_height(ui_Calendar1, lv_pct(100));
    lv_obj_clear_flag(ui_Calendar1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags

    uic_CalendarPage = ui_CalendarPage;

}
