// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_CalendarPage_screen_init(void)
{
    ui_CalendarPage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_CalendarPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CalendarPage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CalendarPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Calendar1 = lv_calendar_create(ui_CalendarPage);
    lv_calendar_set_today_date(ui_Calendar1, 2025, 4, 24);
    lv_calendar_set_showed_date(ui_Calendar1, 2025, 4);
    lv_obj_t * ui_Calendar1_header = lv_calendar_header_arrow_create(ui_Calendar1);
    lv_obj_set_width(ui_Calendar1, lv_pct(100));
    lv_obj_set_height(ui_Calendar1, lv_pct(100));
    lv_obj_clear_flag(ui_Calendar1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags

    ui_btnHome = lv_btn_create(ui_CalendarPage);
    lv_obj_set_width(ui_btnHome, 32);
    lv_obj_set_height(ui_btnHome, 32);
    lv_obj_set_x(ui_btnHome, -65);
    lv_obj_set_y(ui_btnHome, -61);
    lv_obj_set_align(ui_btnHome, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnHome, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnHome, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btnHome, &ui_img_back_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnHome, ui_event_btnHome, LV_EVENT_ALL, NULL);
    uic_CalendarPage = ui_CalendarPage;

}
