// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_HomePage_screen_init(void)
{
    ui_HomePage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HomePage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HomePage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomePage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnMain = lv_btn_create(ui_HomePage);
    lv_obj_set_width(ui_btnMain, lv_pct(100));
    lv_obj_set_height(ui_btnMain, lv_pct(40));
    lv_obj_add_flag(ui_btnMain, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnMain, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnMain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnMain, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_btnMain, 255, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);

    ui_MainArea = lv_textarea_create(ui_btnMain);
    lv_obj_set_width(ui_MainArea, lv_pct(120));
    lv_obj_set_height(ui_MainArea, lv_pct(120));
    lv_obj_set_align(ui_MainArea, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_MainArea, "Place\nv.放置");
    lv_textarea_set_placeholder_text(ui_MainArea, "Placeholder...");
    lv_obj_clear_flag(ui_MainArea, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC);      /// Flags
    lv_obj_set_style_text_align(ui_MainArea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MainArea, &ui_font_ChineseSong16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnWeather = lv_btn_create(ui_HomePage);
    lv_obj_set_width(ui_btnWeather, lv_pct(25));
    lv_obj_set_height(ui_btnWeather, lv_pct(40));
    lv_obj_set_x(ui_btnWeather, lv_pct(0));
    lv_obj_set_y(ui_btnWeather, lv_pct(60));
    lv_obj_add_flag(ui_btnWeather, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnWeather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnWeather, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnWeather, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnWeather, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btnWeather, &ui_img_weather_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnTime = lv_btn_create(ui_HomePage);
    lv_obj_set_width(ui_btnTime, lv_pct(25));
    lv_obj_set_height(ui_btnTime, lv_pct(40));
    lv_obj_set_x(ui_btnTime, lv_pct(25));
    lv_obj_set_y(ui_btnTime, lv_pct(60));
    lv_obj_add_flag(ui_btnTime, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnTime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btnTime, &ui_img_time_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_btnTime, 255, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);

    ui_btnSetting = lv_btn_create(ui_HomePage);
    lv_obj_set_width(ui_btnSetting, lv_pct(25));
    lv_obj_set_height(ui_btnSetting, lv_pct(40));
    lv_obj_set_x(ui_btnSetting, lv_pct(50));
    lv_obj_set_y(ui_btnSetting, lv_pct(60));
    lv_obj_add_flag(ui_btnSetting, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnSetting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnSetting, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnSetting, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnSetting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btnSetting, &ui_img_setting_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnApp = lv_btn_create(ui_HomePage);
    lv_obj_set_width(ui_btnApp, lv_pct(25));
    lv_obj_set_height(ui_btnApp, lv_pct(40));
    lv_obj_set_x(ui_btnApp, lv_pct(75));
    lv_obj_set_y(ui_btnApp, lv_pct(60));
    lv_obj_add_flag(ui_btnApp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnApp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnApp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnApp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnApp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btnApp, &ui_img_qr_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnSecondary = lv_btn_create(ui_HomePage);
    lv_obj_set_width(ui_btnSecondary, lv_pct(100));
    lv_obj_set_height(ui_btnSecondary, lv_pct(20));
    lv_obj_set_x(ui_btnSecondary, lv_pct(0));
    lv_obj_set_y(ui_btnSecondary, lv_pct(40));
    lv_obj_add_flag(ui_btnSecondary, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnSecondary, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnSecondary, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnSecondary, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SecondaryArea = lv_textarea_create(ui_btnSecondary);
    lv_obj_set_width(ui_SecondaryArea, lv_pct(112));
    lv_obj_set_height(ui_SecondaryArea, lv_pct(192));
    lv_obj_set_x(ui_SecondaryArea, lv_pct(-6));
    lv_obj_set_y(ui_SecondaryArea, lv_pct(-45));
    lv_textarea_set_text(ui_SecondaryArea, "中国 福建 福州 24 多云");
    lv_obj_clear_flag(ui_SecondaryArea, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_SecondaryArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SecondaryArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SecondaryArea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SecondaryArea, &ui_font_ChineseSong16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SecondaryArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SecondaryArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SecondaryArea, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SecondaryArea, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnMain, ui_event_btnMain, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnWeather, ui_event_btnWeather, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnTime, ui_event_btnTime, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnSetting, ui_event_btnSetting, LV_EVENT_ALL, NULL);
    uic_HomePage = ui_HomePage;
    uic_btnWordbook = ui_btnMain;
    uic_MainArea = ui_MainArea;
    uic_btnWeather = ui_btnWeather;
    uic_btnTime = ui_btnTime;
    uic_btnSetting = ui_btnSetting;
    uic_btnApp = ui_btnApp;
    uic_btnSecondary = ui_btnSecondary;
    uic_SecondaryArea = ui_SecondaryArea;

}
