// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_SettingPage_screen_init(void)
{
    ui_SettingPage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SettingPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SettingPage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnHome3 = lv_btn_create(ui_SettingPage);
    lv_obj_set_width(ui_btnHome3, 39);
    lv_obj_set_height(ui_btnHome3, 32);
    lv_obj_add_flag(ui_btnHome3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnHome3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnHome3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnHome3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btnHome3, &ui_img_back_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingContainer = lv_obj_create(ui_SettingPage);
    lv_obj_remove_style_all(ui_SettingContainer);
    lv_obj_set_width(ui_SettingContainer, lv_pct(80));
    lv_obj_set_height(ui_SettingContainer, lv_pct(140));
    lv_obj_set_y(ui_SettingContainer, 34);
    lv_obj_set_x(ui_SettingContainer, lv_pct(18));
    lv_obj_clear_flag(ui_SettingContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scroll_dir(ui_SettingContainer, LV_DIR_VER);
    lv_obj_set_style_bg_color(ui_SettingContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiContainer = lv_obj_create(ui_SettingContainer);
    lv_obj_remove_style_all(ui_wifiContainer);
    lv_obj_set_width(ui_wifiContainer, 188);
    lv_obj_set_height(ui_wifiContainer, 35);
    lv_obj_clear_flag(ui_wifiContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_wifiContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifiContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiSwitch = lv_switch_create(ui_wifiContainer);
    lv_obj_set_width(ui_wifiSwitch, 57);
    lv_obj_set_height(ui_wifiSwitch, lv_pct(100));
    lv_obj_set_x(ui_wifiSwitch, lv_pct(67));
    lv_obj_set_y(ui_wifiSwitch, lv_pct(0));
    lv_obj_set_style_bg_color(ui_wifiSwitch, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifiSwitch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_anim_time(ui_wifiSwitch, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_wifiSwitch, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifiSwitch, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_wifiTextArea = lv_textarea_create(ui_wifiContainer);
    lv_obj_set_width(ui_wifiTextArea, lv_pct(64));
    lv_obj_set_height(ui_wifiTextArea, lv_pct(100));
    lv_obj_set_x(ui_wifiTextArea, lv_pct(0));
    lv_obj_set_y(ui_wifiTextArea, lv_pct(-1));
    lv_textarea_set_text(ui_wifiTextArea, "Wifi");
    lv_obj_clear_flag(ui_wifiTextArea, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_wifiTextArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wifiTextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_wifiTextArea, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bleContainer = lv_obj_create(ui_SettingContainer);
    lv_obj_remove_style_all(ui_bleContainer);
    lv_obj_set_width(ui_bleContainer, 188);
    lv_obj_set_height(ui_bleContainer, 35);
    lv_obj_set_x(ui_bleContainer, lv_pct(0));
    lv_obj_set_y(ui_bleContainer, lv_pct(17));
    lv_obj_set_style_bg_color(ui_bleContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bleContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bleSwitch = lv_switch_create(ui_bleContainer);
    lv_obj_set_width(ui_bleSwitch, 57);
    lv_obj_set_height(ui_bleSwitch, lv_pct(100));
    lv_obj_set_x(ui_bleSwitch, lv_pct(67));
    lv_obj_set_y(ui_bleSwitch, lv_pct(0));
    lv_obj_set_style_bg_color(ui_bleSwitch, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bleSwitch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_anim_time(ui_bleSwitch, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_bleSwitch, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bleSwitch, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_bleTextArea = lv_textarea_create(ui_bleContainer);
    lv_obj_set_width(ui_bleTextArea, lv_pct(65));
    lv_obj_set_height(ui_bleTextArea, lv_pct(100));
    lv_obj_set_x(ui_bleTextArea, lv_pct(0));
    lv_obj_set_y(ui_bleTextArea, lv_pct(-1));
    lv_textarea_set_text(ui_bleTextArea, "Bluetooth");
    lv_obj_clear_flag(ui_bleTextArea, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_bleTextArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_bleTextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_bleTextArea, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeContainer = lv_obj_create(ui_SettingContainer);
    lv_obj_remove_style_all(ui_timeContainer);
    lv_obj_set_width(ui_timeContainer, 188);
    lv_obj_set_height(ui_timeContainer, 35);
    lv_obj_set_x(ui_timeContainer, lv_pct(0));
    lv_obj_set_y(ui_timeContainer, lv_pct(33));

    ui_timeModeSwitch = lv_switch_create(ui_timeContainer);
    lv_obj_set_width(ui_timeModeSwitch, 57);
    lv_obj_set_height(ui_timeModeSwitch, lv_pct(100));
    lv_obj_set_x(ui_timeModeSwitch, lv_pct(67));
    lv_obj_set_y(ui_timeModeSwitch, lv_pct(0));
    lv_obj_set_style_bg_color(ui_timeModeSwitch, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_timeModeSwitch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_anim_time(ui_timeModeSwitch, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_timeModeSwitch, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_timeModeSwitch, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_timeTextArea = lv_textarea_create(ui_timeContainer);
    lv_obj_set_width(ui_timeTextArea, lv_pct(65));
    lv_obj_set_height(ui_timeTextArea, lv_pct(100));
    lv_obj_set_x(ui_timeTextArea, lv_pct(0));
    lv_obj_set_y(ui_timeTextArea, lv_pct(-1));
    lv_textarea_set_text(ui_timeTextArea, "TimeMode");
    lv_obj_clear_flag(ui_timeTextArea, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_timeTextArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_timeTextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_timeTextArea, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_memorandumContainer = lv_obj_create(ui_SettingContainer);
    lv_obj_remove_style_all(ui_memorandumContainer);
    lv_obj_set_width(ui_memorandumContainer, 188);
    lv_obj_set_height(ui_memorandumContainer, 35);
    lv_obj_set_x(ui_memorandumContainer, lv_pct(0));
    lv_obj_set_y(ui_memorandumContainer, lv_pct(50));
    lv_obj_add_flag(ui_memorandumContainer,
                    LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_FLOATING | LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags

    ui_memorandumSwitch = lv_switch_create(ui_memorandumContainer);
    lv_obj_set_width(ui_memorandumSwitch, 57);
    lv_obj_set_height(ui_memorandumSwitch, lv_pct(100));
    lv_obj_set_x(ui_memorandumSwitch, lv_pct(67));
    lv_obj_set_y(ui_memorandumSwitch, lv_pct(0));
    lv_obj_set_style_anim_time(ui_memorandumSwitch, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_memorandumSwitch, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_memorandumSwitch, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_memorandumTextArea = lv_textarea_create(ui_memorandumContainer);
    lv_obj_set_width(ui_memorandumTextArea, lv_pct(51));
    lv_obj_set_height(ui_memorandumTextArea, lv_pct(169));
    lv_obj_set_x(ui_memorandumTextArea, lv_pct(0));
    lv_obj_set_y(ui_memorandumTextArea, lv_pct(-1));
    lv_textarea_set_text(ui_memorandumTextArea, "memorandum");
    lv_obj_clear_flag(ui_memorandumTextArea,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_memorandumTextArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_memorandumTextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_memorandumTextArea, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnHome3, ui_event_btnHome3, LV_EVENT_ALL, NULL);
    uic_SettingPage = ui_SettingPage;
    uic_SettingContainer = ui_SettingContainer;
    uic_wifiContainer = ui_wifiContainer;
    uic_bleContainer = ui_bleContainer;
    uic_bleSwitch = ui_bleSwitch;
    uic_bleTextArea = ui_bleTextArea;
    uic_timeContainer = ui_timeContainer;
    uic_timeSwitch = ui_timeModeSwitch;
    uic_timeTextArea = ui_timeTextArea;
    uic_memorandumContainer = ui_memorandumContainer;
    uic_memorandumSwitch = ui_memorandumSwitch;
    uic_memorandumTextArea = ui_memorandumTextArea;

}
