// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"



// 修改现有的ui_SettingPage_screen_init函数，添加事件绑定
void ui_SettingPage_screen_init(void) {
    ui_SettingPage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SettingPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SettingPage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnHome3 = lv_btn_create(ui_SettingPage);
    lv_obj_set_width(ui_btnHome3, 32);
    lv_obj_set_height(ui_btnHome3, 32);
    lv_obj_add_flag(ui_btnHome3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnHome3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnHome3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnHome3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btnHome3, &ui_img_back_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiContainer = lv_obj_create(ui_SettingPage);
    lv_obj_remove_style_all(ui_wifiContainer);
    lv_obj_set_width(ui_wifiContainer, 152);
    lv_obj_set_height(ui_wifiContainer, 35);
    lv_obj_set_x(ui_wifiContainer, -8);
    lv_obj_set_y(ui_wifiContainer, -27);
    lv_obj_set_align(ui_wifiContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_wifiContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifiSwitch = lv_switch_create(ui_wifiContainer);
    lv_obj_set_width(ui_wifiSwitch, 57);
    lv_obj_set_height(ui_wifiSwitch, lv_pct(100));
    lv_obj_set_x(ui_wifiSwitch, lv_pct(60));
    lv_obj_set_y(ui_wifiSwitch, lv_pct(0));
    lv_obj_set_style_anim_time(ui_wifiSwitch, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_wifiSwitch, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifiSwitch, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_wifiTextArea = lv_textarea_create(ui_wifiContainer);
    lv_obj_set_width(ui_wifiTextArea, lv_pct(50));
    lv_obj_set_height(ui_wifiTextArea, lv_pct(100));
    lv_obj_set_x(ui_wifiTextArea, lv_pct(0));
    lv_obj_set_y(ui_wifiTextArea, lv_pct(-1));
    lv_textarea_set_text(ui_wifiTextArea, "Wifi");
    lv_obj_clear_flag(ui_wifiTextArea, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_wifiTextArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wifiTextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_wifiTextArea, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnHome3, ui_event_btnHome3, LV_EVENT_ALL, NULL);
    uic_SettingPage = ui_SettingPage;
    uic_wifiContainer = ui_wifiContainer;
    
}
