// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_WeatherPage_screen_init(void)
{
    ui_WeatherPage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_WeatherPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WeatherPage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WeatherPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_WeatherPage, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WeatherPage, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_WeatherChart = lv_chart_create(ui_WeatherPage);
    lv_obj_set_width(ui_WeatherChart, lv_pct(80));
    lv_obj_set_height(ui_WeatherChart, lv_pct(60));
    lv_obj_set_x(ui_WeatherChart, lv_pct(11));
    lv_obj_set_y(ui_WeatherChart, lv_pct(24));
    lv_chart_set_type(ui_WeatherChart, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_WeatherChart, 7);
    lv_chart_set_range(ui_WeatherChart, LV_CHART_AXIS_PRIMARY_Y, 10, 40);
    lv_chart_set_div_line_count(ui_WeatherChart, 10, 7);
    lv_chart_set_zoom_x(ui_WeatherChart, 250);
    lv_chart_set_zoom_y(ui_WeatherChart, 256);
    lv_chart_set_axis_tick(ui_WeatherChart, LV_CHART_AXIS_PRIMARY_X, 5, 0, 8, 2, true, 10);
    lv_chart_set_axis_tick(ui_WeatherChart, LV_CHART_AXIS_PRIMARY_Y, 5, 3, 4, 5, true, 50);
    lv_chart_set_axis_tick(ui_WeatherChart, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 5, 2, false, 25);
    lv_chart_series_t * ui_WeatherChart_series_1 = lv_chart_add_series(ui_WeatherChart, lv_color_hex(0x000000),
                                                                       LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_WeatherChart_series_1_array[] = { 12, 32, 24, 22 };
    lv_chart_set_ext_y_array(ui_WeatherChart, ui_WeatherChart_series_1, ui_WeatherChart_series_1_array);

    ui_TextArea1 = lv_textarea_create(ui_WeatherPage);
    lv_obj_set_width(ui_TextArea1, 190);
    lv_obj_set_height(ui_TextArea1, 35);
    lv_obj_set_x(ui_TextArea1, 4);
    lv_obj_set_y(ui_TextArea1, -71);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea1, "Weather in next 7 days");
    lv_textarea_set_placeholder_text(ui_TextArea1, "Placeholder...");

    ui_btnHome1 = lv_btn_create(ui_WeatherPage);
    lv_obj_set_width(ui_btnHome1, 32);
    lv_obj_set_height(ui_btnHome1, 32);
    lv_obj_add_flag(ui_btnHome1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnHome1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnHome1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnHome1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btnHome1, &ui_img_back_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnHome1, ui_event_btnHome1, LV_EVENT_ALL, NULL);
    uic_WeatherChart = ui_WeatherChart;

}
